name: Cherry-Pick to Master

on:
  pull_request:
    types:
      - labeled

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: github.event.label.name == 'CherryPickForRelease'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      # - name: Set up Git
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run: |
        #   git config --global user.name 'github-actions[bot]'
        #   git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Cherry pick into release-v2.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: ${{github.event.pull_request.head.ref}}
          labels: CherryPickForRelease
          title: '[cherry-pick] {old_title}'
          body: 'Cherry-pick #{old_pull_request_id} to main'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "A cherry-pick PR has been created against the master branch: ${{steps.new-issue.outputs.html_url}}"
          reactions: '+1'
